"""empty message

Revision ID: 09de137e6125
Revises: e338971af6f6
Create Date: 2020-08-13 20:22:02.591430-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09de137e6125'
down_revision = 'e338971af6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criminal_complaints', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'criminal_complaints', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'criminal_complaints', type_='foreignkey')
    op.drop_column('criminal_complaints', 'created_by')
    # ### end Alembic commands ###
