"""empty message

Revision ID: 2528fcda638b
Revises: cad38e0fb46d
Create Date: 2020-08-18 08:02:17.092648-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2528fcda638b'
down_revision = 'cad38e0fb46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criminal_complaints', sa.Column('aws_bucket', sa.String(), nullable=True))
    op.add_column('criminal_complaints', sa.Column('img_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criminal_complaints', 'img_key')
    op.drop_column('criminal_complaints', 'aws_bucket')
    # ### end Alembic commands ###
