"""empty message

Revision ID: 3ae92f52bdb4
Revises: f016e5d4c916
Create Date: 2020-08-27 18:07:38.511019-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae92f52bdb4'
down_revision = 'f016e5d4c916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
