"""empty message

Revision ID: 43e63cc58a0e
Revises: 54890a67eddd
Create Date: 2020-08-13 20:14:21.946438-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43e63cc58a0e'
down_revision = '54890a67eddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criminal_complaints', sa.Column('created_by_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('criminal_complaints_created_by_fkey', 'criminal_complaints', type_='foreignkey')
    op.create_foreign_key(None, 'criminal_complaints', 'users', ['created_by_id'], ['id'])
    op.drop_column('criminal_complaints', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criminal_complaints', sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'criminal_complaints', type_='foreignkey')
    op.create_foreign_key('criminal_complaints_created_by_fkey', 'criminal_complaints', 'users', ['created_by'], ['id'])
    op.drop_column('criminal_complaints', 'created_by_id')
    # ### end Alembic commands ###
