"""add ddi table

Revision ID: 542d280a0884
Revises: 49d0e058ad13
Create Date: 2022-10-14 14:48:05.510483-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '542d280a0884'
down_revision = '49d0e058ad13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defendant_demographic_info',
    sa.Column('ddi_id', sa.Integer(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ddi_id')
    )
    op.create_index(op.f('ix_defendant_demographic_info_ddi_id'), 'defendant_demographic_info', ['ddi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defendant_demographic_info_ddi_id'), table_name='defendant_demographic_info')
    op.drop_table('defendant_demographic_info')
    # ### end Alembic commands ###
