"""empty message

Revision ID: 54890a67eddd
Revises: ea8390c539e3
Create Date: 2020-08-13 19:55:26.799268-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54890a67eddd'
down_revision = 'ea8390c539e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
