"""empty message

Revision ID: c9a992f438d9
Revises: 43e63cc58a0e
Create Date: 2020-08-13 20:16:39.401213-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a992f438d9'
down_revision = '43e63cc58a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
