"""empty message

Revision ID: d23c4513a1bc
Revises: 09de137e6125
Create Date: 2020-08-14 11:35:18.120245-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23c4513a1bc'
down_revision = '09de137e6125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criminal_complaints', sa.Column('defen_adr', sa.String(), nullable=True))
    op.add_column('criminal_complaints', sa.Column('defen_name', sa.String(), nullable=True))
    op.add_column('criminal_complaints', sa.Column('offense_codes', sa.String(), nullable=True))
    op.add_column('criminal_complaints', sa.Column('raw_text', sa.String(), nullable=True))
    op.drop_column('criminal_complaints', 'defen_name_adr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criminal_complaints', sa.Column('defen_name_adr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('criminal_complaints', 'raw_text')
    op.drop_column('criminal_complaints', 'offense_codes')
    op.drop_column('criminal_complaints', 'defen_name')
    op.drop_column('criminal_complaints', 'defen_adr')
    # ### end Alembic commands ###
