"""empty message

Revision ID: e338971af6f6
Revises: c9a992f438d9
Create Date: 2020-08-13 20:17:07.951639-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e338971af6f6'
down_revision = 'c9a992f438d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('criminal_complaints_created_by_id_fkey', 'criminal_complaints', type_='foreignkey')
    op.drop_column('criminal_complaints', 'created_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criminal_complaints', sa.Column('created_by_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('criminal_complaints_created_by_id_fkey', 'criminal_complaints', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###
