"""empty message

Revision ID: e6c3fe333af5
Revises: 3ae92f52bdb4
Create Date: 2020-08-27 20:11:27.760397-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c3fe333af5'
down_revision = '3ae92f52bdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
