"""empty message

Revision ID: f016e5d4c916
Revises: a68575ccc5b9
Create Date: 2020-08-19 12:11:04.677188-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f016e5d4c916'
down_revision = 'a68575ccc5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_county_authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_county_authorized')
    # ### end Alembic commands ###
